---
title: "Abstract"
author: "Skip Moses"
date: "4/17/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Data often has an underlying structure of Geometry that can be modeled a signal on the vertices of a weighted, undirected graph. There are several analogies between traditional signal processing an algebraic graph theory that translates many of the tools of discrete signal processing such as spectral analysis of multichannel signals, system transfer function, and digital filter design to name a few. Historically, GSP has focused on modeling smooth signals on a graph, but the increase in availability of abstract data sets has motivated algorithms for learning a valid graph given a set of signals. In this work we attempt to design such an algorithm for learning a valid graph topology given a set of binomial signals. This is accomplished by extending the ideas of Conditional Logistic Regression and Maximum Likelihood with constraints that enforce a valid graph topology on the regression coefficient matrix. 